### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by ryanccn** [JettChenT/Encrypto#2]
<img width="752" alt="Screen Shot 2020-05-30 at 10 52 43" src="https://user-images.githubusercontent.com/47623453/83318014-b461ed00-a263-11ea-80e1-6f70469fac8f.png">

Please add [flask-cors](https://github.com/corydolphin/flask-cors) to the Flask app.

Also pls migrate quickly from Encrypto_api to Encrypto @JettChenT !

**Comment by JettChenT** [comment]
@ryanccn  *CORS* added now🙂

**Comment by ryanccn** [comment]
Whoop whoop
