### ISSUE TITLE
Client-side operations

### ISSUE THREAD

**Issue by ryanccn** [JettChenT/Encrypto#3]
> I am not sure if people shouldn't worry about security issues when they are sending their messages to a service which encrypts and decrypts it (this is really concerning). The first problem I see: You posted a link to your service with `http-only` instead of `https` and the message gets sent to your server as clear text. So if people would use `http`, everyone in between could read everything.

> You should try to move the step of encryption and hashing client-side via Javascript for example. So that your service would only store hashes and keys.

> From Reddit

Implement this feature?

**Comment by ryanccn** [comment]
This will be much more secure

**Comment by JettChenT** [comment]
Could be viable. I'll add that to the feature list. @ryanccn
